### ISSUE TITLE
info method

### ISSUE THREAD

**Issue by dangiger** [719Ben/myCUinfo-API#13]
The method info() is not working. Perhaps this is because CU changed the way they display user information, here is the error I get when running this code.

Note: This works fine when I use the classes() method.

`        loginUser = mycuinfo.CUSession(user, password)`
`       userinfo = loginUser.info()
`

> Traceback (most recent call last):
  File "/Users/<>/PycharmProjects/untitled/main", line 19, in <module>
    main()
  File "/Users/<>/PycharmProjects/untitled/main", line 10, in main
    userinfo = loginUser.info()
  File "/usr/local/lib/python2.7/site-packages/mycuinfo/cusession.py", line 149, in info
    name = item.split('<')[1].split('>')[0]
IndexError: list index out of range

**Comment by biw** [comment]
Is there anything that doesn't make you a standard student (more than one major, more than one college, student employee, no student ID, etc.)?
